env:
  es2020: true
  node: true
  jest: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
settings:
  'import/resolver':
    node:
      paths: ['src']
      extensions: [".js", ".ts"]
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'import'
  - 'jest'
rules:
  no-console: off
  import/extensions: off
